doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        url: '%env(resolve:DB_URL)%'
        driver: 'pdo_pgsql'
        server_version: '14.2'
        charset: UTF8
        default_table_options:
          charset: UTF8
          collate: UTF8
        mapping_types:
          enum: string
    types:
      # Core context
      actor_id: Whalar\Core\Infrastructure\Persistence\Doctrine\Type\ActorIdType
      seasons_active: Whalar\Core\Infrastructure\Persistence\Doctrine\Type\SeasonsActiveType
      character_id: Whalar\Core\Infrastructure\Persistence\Doctrine\Type\CharacterIdType
      royal: Whalar\Core\Infrastructure\Persistence\Doctrine\Type\RoyalType
      kings_guard: Whalar\Core\Infrastructure\Persistence\Doctrine\Type\KingsGuardType
      character_relation: Whalar\Core\Infrastructure\Persistence\Doctrine\Type\CharacterRelationType

      # Shared context
      aggregate_id: Whalar\Shared\Infrastructure\Persistence\Doctrine\Type\AggregateIdType
      carbontz_immutable: Whalar\Shared\Infrastructure\Persistence\Doctrine\Type\CarbonTzImmutableType
      message_id: Whalar\Shared\Infrastructure\Persistence\Doctrine\Type\MessageIdType
      name: Whalar\Shared\Infrastructure\Persistence\Doctrine\Type\NameType
      image_url: Whalar\Shared\Infrastructure\Persistence\Doctrine\Type\ImageUrlType

  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      core_context:
        mapping: true
        is_bundle: false
        type: yml
        dir: '%kernel.project_dir%/src/Core/Infrastructure/Persistence/Doctrine/Entity'
        prefix: 'Whalar\Core'
      shared_context:
        mapping: true
        is_bundle: false
        type: yml
        dir: '%kernel.project_dir%/src/Shared/Infrastructure/Persistence/Doctrine/Entity'
        prefix: 'Whalar\Shared'
