# Core context
whalar.core:
    resource: ./routes/v1_core_routes.yaml
    prefix: /v1

# Shared context
whalar.shared:
    resource: ./routes/shared_routes.yaml

# Api Platform
api_platform:
    resource: .
    type: api_platform
    prefix: /api
