version: '3.7'

services:
  app:
    container_name: whalar-fvalverde-app
    build:
      dockerfile: .deployment/docker/app/Dockerfile
      context: ./../../
      target: debug
    user: "1000:1000"
    depends_on:
      - db
    working_dir: /var/www/html
    volumes:
      - ./../../:/var/www/html

  http_server:
    container_name: whalar-fvalverde-http-server
    build:
      dockerfile: .deployment/docker/httpServer/Dockerfile
      context: ./../../
    working_dir: /var/www/html
    depends_on:
      - app
    volumes:
      - ./../../:/var/www/html:ro
    ports:
      - "8080:80"

  db:
    container_name: whalar-fvalverde-db
    hostname: db
    image: postgres:14.2-alpine3.15
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env

  adminer:
    container_name: whalar-fvalverde-adminer
    image: adminer:4.8.1
    ports:
      - "8001:8080"

  rabbitmq:
    container_name: whalar-fvalverde-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    hostname: rabbitmq
    image: rabbitmq:3.12-rc-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - .deployment/docker/relk/rabbitmq/config/custom_definitions.json:/opt/definitions.json:ro
      - .deployment/docker/relk/rabbitmq/config/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro

  elasticsearch:
    image: elasticsearch:8.9.2
    container_name: whalar-fvalverde-elasticsearch
    ports: [ '9200:9200' ]
    environment:
      - "ELASTIC_PASSWORD=elastic"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.type=single-node"
      - "TAKE_FILE_OWNERSHIP=1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - './var/elasticsearch:/usr/share/elasticsearch/data'

  logstash:
    container_name: whalar-fvalverde-logstash
    environment:
      - "ELASTIC_PASSWORD=elastic"
    build:
      dockerfile: .deployment/docker/relk/logstash/Dockerfile
      context: ./../../
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    ports:
      - "5001:5000"
    links:
      - elasticsearch
      - rabbitmq

  kibana:
    container_name: whalar-fvalverde-kibana
    image: kibana:8.9.2
    environment:
      - "ELASTIC_PASSWORD=elastic"
    ports: [ '5601:5601' ]
    depends_on:
      - elasticsearch